name: Semantic Release

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    env:
      CI: true
      NODE_ENV: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm run lint
      - run: npm test
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
