name: Test

on:
  pull_request:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test:
    env:
      CI: true
      NODE_ENV: test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 20

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm run lint
      - run: npm test
